### ISSUE TITLE
the link of the best model can't be opened

### ISSUE THREAD

**Issue by zhucongying** [captanlevi/Contour-Detection-Pytorch#1]
Hi, the link of the best model can't be opened, can you send the model to my email congyingzhu@163.com

**Comment by captanlevi** [comment]
hello , i am o sorry for the late response. dont know if this helps but here is the link
https://drive.google.com/file/d/1-T5ZUu45O_76IxWlSp8RXGSPlQ-BZ288/view?usp=sharing
