### ISSUE TITLE
Problem of Q.put

### ISSUE THREAD

**Issue by krapeun** [captanlevi/Contour-Detection-Pytorch#10]
Hello, thank you for your great code.

I have some problem about 'Q' which loads data.
It can't put data (Q.put doesn't work), so in start_training, shared_Q is always empty.
I don't know why it doesn't work even though I think both image and text files exist.

![image](https://user-images.githubusercontent.com/62520045/123118851-f583fb00-d47d-11eb-9f02-380590faf66b.png)

Have you ever had a problem like this or can you help me?
Thank you again :)

**Comment by captanlevi** [comment]
Hello, sorry for the late reply. I have not had any such issues. I would suggest making your own dataloader class and implement all those methods without using multiprocessing .

**Comment by kulkarnikeerti** [comment]
Hi @krapeun I have encountered the same issue. Did you resolve the issue? or were you able to find solution for this problem?

Thanks
