### ISSUE TITLE
DenseCRF refined segmantation maps for PASCAL-2012 dataset

### ISSUE THREAD

**Issue by maryami66** [captanlevi/Contour-Detection-Pytorch#11]
Thank you for sharing your work!
I am interested in applying this model. In Readme it is said: Download the DenseCRF refined segmantation maps for PASCAL-2012 dataset. And place them in SegmentationObjectFilledDenseCRF folder.

Could you please let me know where can I find it?

**Comment by captanlevi** [comment]
you can get the dataset from kaggle https://www.kaggle.com/huanghanchina/pascal-voc-2012

**Comment by maryami66** [comment]
> you can get the dataset from kaggle https://www.kaggle.com/huanghanchina/pascal-voc-2012

Thank you!

**Comment by kulkarnikeerti** [comment]
Hi @maryami66 @captanlevi 

I bumped into a same question. I can find the dataset in kaggle. But the Segmentation Object folder in kaggle has 2913 images where as the training file contains 10500 samples. Where can I find the rest of the dataset? 

Thanks in advance
