### ISSUE TITLE
Segmentation maps for Pascal - 2012?

### ISSUE THREAD

**Issue by kulkarnikeerti** [captanlevi/Contour-Detection-Pytorch#19]
Hi @captanlevi 

Thanks for the  great work. I can access the segmentation maps for Pascal-2012 dataset from kaggle. But the segmentation object folder contain just 2931 images, where can I access the other images? Original images are around 17k. 

Thanks in advance

**Comment by captanlevi** [comment]
Hello, I am not sure as to where you can find the data right now, I you can find the data, please let me know as well.

**Comment by kulkarnikeerti** [comment]
Thanks
