### ISSUE TITLE
RuntimeError: Given groups=1, weight of size [64, 3, 3, 3], expected input[2, 224, 224, 3] to have 3 channels, but got 224 channels instead

### ISSUE THREAD

**Issue by kulkarnikeerti** [captanlevi/Contour-Detection-Pytorch#20]
Hi @captanlevi

I had the issue with the multiprocessing as mentions in [this](https://github.com/captanlevi/Contour-Detection-Pytorch/issues/10). And I followed your suggestion to create a dataloader without  mutliprocessing. But I end with the mentioned error in below line.

https://github.com/captanlevi/Contour-Detection-Pytorch/blob/e3e6c90a157c945b8762121ac15c5add96aa60fb/net.py#L57

I am using (224, 224) as image size. Could you please suggest me what I should be checking when I have this error?
Thanks in advance

**Comment by captanlevi** [comment]
Hello, you need your images to be in the 3D shape.
As in not (224,224) but (1,224,224).
Reshaping can resolve your issue.

Other than that as there is a little interest in this project. I will be launching a new code with new features in the next few days.

**Comment by kulkarnikeerti** [comment]
@captanlevi Thanks, that helped.
And thanks for letting me know about the new features. I suppose the new features will be added in the same repository, or will there be a new repository for that?

And just one last question about this model. I am getting negative loss values. Do you have any suggestions for this? or is this a normal behavior?
Thanks

**Comment by captanlevi** [comment]
I will work in the same repo, for the negative loss perhaps you have not normalised the images ?

**Comment by kulkarnikeerti** [comment]
Yeah, I haven't normalized the images. I am using albumentations for augmentation and I tried to normalize it in the same way. But this didn't help. 

Just to clarify, is this how you normalize the images in this code? or I missed that part of code? Because I use the same values for normalization in albumentations but that didn't help me.
https://github.com/captanlevi/Contour-Detection-Pytorch/blob/e3e6c90a157c945b8762121ac15c5add96aa60fb/train.py#L101

**Comment by kulkarnikeerti** [comment]
Okay. I figured it out. Thanks:)
