### ISSUE TITLE
Targets used for the model?

### ISSUE THREAD

**Issue by kulkarnikeerti** [captanlevi/Contour-Detection-Pytorch#22]
Hi @captanlevi 

I have encountered one more doubt while trying to use my own dataset.

https://github.com/captanlevi/Contour-Detection-Pytorch/blob/e3e6c90a157c945b8762121ac15c5add96aa60fb/train.py#L24

From the mentioned code I understand that the targets to the model are the segmented images not the `improved_contours`   (extracted from the given script). In this case how does the model learns to predict specific boundary for a given object? And where exactly these extracted contour images (`improved_contours`) are used. Because I don't see anywhere its used.

Thanks again

**Comment by captanlevi** [comment]
So the training is in fact done on the improved contours.  
So it goes this way, we construct edges from the dense filled images. And then the training is done on the edge images

**Comment by captanlevi** [comment]
I might have made an error in defining the target path, sorry for this

**Comment by kulkarnikeerti** [comment]
Ah okay. So for training targets are `improved_contours`. Got it! Thanks:)
